project_name: envoy-auth
namespace: envoy-auth
auth_service:
  name: auth-service
  namespace: envoy-auth
  gateway:
    uri_prefix: /api/auth/
  deployment:
    replicas: 1
    image: waterfogsw/auth-server:1.0.3
    container_port: 8000
  service:
    port: 8000

echo_service:
  name: echo-service
  namespace: envoy-auth
  gateway:
    uri_prefix: /api/echo/
  deployment:
    replicas: 1
    image: waterfogsw/echo-server:1.0.0
    container_port: 8000
  service:
    port: 8000

jwt:
  jwks_endpoint: http://auth-service.envoy-auth.svc.cluster.local:8000/.well-known/jwks.json