FROM python:3.11-slim as builder
RUN pip install poetry
COPY pyproject.toml poetry.lock ./app/
COPY src ./app/src
WORKDIR ./app
RUN poetry config virtualenvs.in-project true \
    && poetry build

FROM python:3.11-slim-buster AS runtime
WORKDIR /app
COPY --from=builder app/dist /dist
RUN pip install /dist/*.whl
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
